name: 'Create Deployment'
description: 'Creates a Deployment in GitHub.'
inputs:
  repo:
    description: 'format: {owner}/{name}'
    required: true
  ref:
    description: 'The git reference for the deployment (tag, branch, commit SHA)'
    required: true
  task:
    description: 'The task for the deployment (e.g., deploy, deploy:migrations, build, test)'
    required: false
    default: 'deploy'
  environment:
    description: 'The environment for the deployment (e.g., production, staging)'
    required: true
  description:
    description: 'A brief description of the deployment'
    required: false
    default: ''
  workflow:
    description: 'The name of the workflow that triggered the deployment'
    required: true
  workflow_details:
    description: 'Additional details about the workflow that triggered the deployment'
    required: false
    default: ''
  workflow_url:
    description: 'The URL of the workflow that triggered the deployment'
    required: false
    default: ''
  initial_state:
    description: 'The initial state of the deployment'
    type: option
    options:
      - error
      - failure
      - inactive
      - in_progress
      - queued
      - pending
      - success
    required: true
outputs:
  Deployment_ID:
    description: 'The ID of the created deployment'
    value: ${{ env.Deployment_ID }}
  Deployment_URL:
    description: 'The URL of the created deployment'
    value: ${{ env.Deployment_URL }}
  Deployment_STATUSES_URL:
    description: 'The statuses URL of the created deployment'
    value: ${{ env.Deployment_STATUSES_URL }}
  Deployment:
    description: 'The full deployment object of the created deployment'
    value: ${{ env.Deployment }}
  Deployment_Status:
    description: 'The status of the created deployment'
    value: ${{ env.Deployment_Status }}
runs:
  using: "composite"
  steps:
    - name: Check jq version and location
      shell: bash
      run: |
        # Print the version string
        jq --version
        
        # Print the exact binary path being used
        which jq
    - name: Add Deployment
      id: add-deployment
      uses: nick-fields/retry@v4
      with:
        timeout_minutes: 10
        max_attempts: 3
        shell: bash
        command: |
            # Print the version string
            jq --version
            
            # Print the exact binary path being used
            which jq
            deployment=$(gh api "repos/${{ inputs.repo }}/deployments" \
            -H "Accept: application/vnd.github+json" \
            -f "ref=${{ inputs.ref }}" \
            -f 'payload={ 
              "workflow": "${{ inputs.workflow }}",
              "workflow_ref": "${{ github.ref }}", 
              "workflow_details": "${{ inputs.workflow_details }}",
              "workflow_url": "${{ inputs.workflow_url }}",
              "initial_state": "${{ inputs.initial_state }}"
            }' \
            -f "environment=${{ inputs.environment }}" \
            -f "description=${{ inputs.description }}" \
            -f "task=${{ inputs.task }}" \
            -F "auto_merge=false" \
            -f "required_contexts[]" \
            -F "production_environment=true" \
            | jq --compact-output'.' \
            )
            id=$(echo "$deployment" | jq -r '.id')
            url=$(echo "$deployment" | jq -r '.url')
            statuses_url=$(echo "$deployment" | jq -r '.statuses_url')
            
            echo -e "Deployment:\n$(echo "$deployment" | jq '.')"
            echo -e "Deployment (compact):\n${deployment}"
            echo "id: ${id}"
            echo "url: ${url}"
            echo "statuses_url: ${statuses_url}"
            echo "Deployment=${deployment}" >> $GITHUB_ENV
            echo "Deployment_URL=${url}" >> $GITHUB_ENV
            echo "Deployment_STATUSES_URL=${statuses_url}" >> $GITHUB_ENV
            echo "Deployment_ID=${id}" >> $GITHUB_ENV
    - name: Add Status
      if: ${{ success() && inputs.initial_state != '' }}
      uses: CDCR-OMS-PVDTS/.github/.github/actions/Set-Deployment-Status@29474-DeploymentActions
      # uses: ./.github/actions/Set-Deployment-Status
      with:
        repo: ${{ inputs.repo }}
        deployment_id: ${{ env.Deployment_ID }}
        state: ${{ inputs.initial_state }}
        description: "Initial deployment status"