name: 'Set Git Tag'
description: 'Sets a git tag in a GitHub repo.'
inputs:
  repo:
    description: 'format: {owner}/{name}'
    required: true
  ref:
    description: 'the ref to add the tag at'
    required: true
  tag:
    description: 'The tag to create'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Tag
      shell: bash
      run: |
        echo "inputs.ref: ${{ inputs.ref }}"
        # urlencode the ref
        url_ref=$(jq -rn '"${{ inputs.ref }}"|@uri')
        echo "url_ref: $url_ref"

        #*************************
        # Find the sha for the ref (including confirming it for a sha ref)
        #*************************
        sha=$(gh api "repos/${{ inputs.repo }}/git/refs/tags/$url_ref" | jq -r '.object.sha') || sha=""
        echo "sha of ref as tag: $sha"

        if [[ -z "${sha}" ]]; then
          sha=$(gh api "repos/${{ inputs.repo }}/git/refs/heads/$url_ref" | jq -r '.object.sha') || sha=""
          echo "sha of ref as branch: $sha"
        fi

        if [[ -z "${sha}" ]]; then
          sha=$(gh api "repos/${{ inputs.repo }}/commits/$url_ref" | jq -r '.sha') || sha=""
          echo "sha of ref as sha: $sha"
        fi
        echo "sha: $sha"

        #*************************
        # Now add or update the tag in GitHub
        #*************************
        echo "inputs.tag: ${{ inputs.tag }}"
        # urlencode the tag
        url_tag=$(jq -rn '"${{ inputs.tag }}"|@uri')
        echo "url_tag: $url_tag"

        tag_sha=$(gh api "repos/${{ inputs.repo }}/git/refs/tags/$url_tag" | jq -r '.object.sha') || sha=""
        echo "sha of tag: $tag_sha"

        if [[ -z "${tag_sha}" ]]; then
          echo "Adding refs/tags/${{ inputs.tag }} to $sha"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ inputs.repo }}/git/refs \
            -f "ref=refs/tags/${{ inputs.tag }}" -f "sha=$sha"
        elif [ "${tag_sha}" != "${sha}" ]; then
          echo "Updating refs/tags/${{ inputs.tag }} from tag_sha to $sha"
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ inputs.repo }}/git/refs/REF/tags/${{ inputs.tag }} \
            -f "sha=${sha}" -F "force=true"
        fi
