name: 'Set Git Tag'
description: 'Sets a git tag in a GitHub repo.'
inputs:
  repo:
    description: 'format: {owner}/{name}'
    required: true
  ref:
    description: 'the ref to add the tag at'
    required: true
  tag:
    description: 'The tag to create'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Tag
      shell: bash
      run: |
        echo "inputs.ref: ${{ inputs.ref }}"
        # urlencode the ref
        url_ref=$(jq -rn '"${{ inputs.ref }}"|@uri')
        echo "url_ref: $url_ref"




        #sha=$(gh api "repos/${{ inputs.repo }}/git/refs/tags" | jq -r '.[] | select(.ref=="refs/tags/${{ inputs.ref }}") | .object.sha')
        sha=$(gh api "repos/CDCR-OMS-PVDTS/.github/git/refs/tags/$url_ref" | jq -r '.object.sha')
        echo "tag sha: $sha"
        if [[ -z "${sha}" ]]; then
          #sha=$(gh api "repos/${{ inputs.repo }}/git/refs/heads" | jq -r '.[] | select(.ref=="refs/heads/${{ inputs.ref }}") | .object.sha')
          sha=$(gh api "repos/CDCR-OMS-PVDTS/.github/git/refs/heads/$url_ref" | jq -r '.object.sha')
          echo "branch sha: $sha"
        fi
        if [[ -z "${sha}" ]]; then
          sha=$(gh api "repos/CDCR-OMS-PVDTS/.github/commits/$url_ref" | jq -r '.sha')
          echo "sha sha: $sha"
        fi
        echo "sha: $sha"

        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ inputs.repo }}/git/refs \
          -f "ref=refs/tags/${{ inputs.tag }}" -f "sha=$sha"