name: 'Set Git Tag'
description: 'Sets a git tag in a GitHub repo.'
inputs:
  repo:
    description: 'format: {owner}/{name}'
    required: true
  ref:
    description: 'the ref to add the tag at'
    required: true
  tag:
    description: 'The tag to create'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Tag
      shell: bash
      run: |
        echo "aaaaaaaaaaaaaaaaaaa"
        gh api "repos/${{ inputs.repo }}/git/refs/tags" | jq -r '.[] | select(.ref>"")'
        echo "bbbbbbbbbbbbbbbbbbb"
        gh api "repos/${{ inputs.repo }}/git/refs/tags" | jq -r '.[] | select(.ref=="")'
        echo "ccccccccccccccccccc"
        gh api "repos/${{ inputs.repo }}/git/refs/tags" | jq -r '.[] | select(.ref=="refs/tags/RunWorkflow.v.1.0.0")'
        echo "ddddddddddddddddddd"
        echo "inputs.ref: ${{ inputs.ref }}"
        gh api "repos/${{ inputs.repo }}/git/refs/tags" | jq -r '.[] | select(.ref=="refs/tags/${{ inputs.ref }}")'
        echo "eeeeeeeeeeeeeeeeeee"
        gh api "repos/${{ inputs.repo }}/git/refs/tags" | jq -r '.[] | select(.ref=="refs/tags/${{ inputs.ref }}") | .object'
        echo "fffffffffffffffffff"
        gh api "repos/${{ inputs.repo }}/git/refs/tags" | jq -r '.[] | select(.ref=="refs/tags/${{ inputs.ref }}") | .object.sha'
        echo "ggggggggggggggggggg"
        sha=(gh api "repos/${{ inputs.repo }}/git/refs/tags" | jq -r '.[] | select(.ref=="refs/tags/${{ inputs.ref }}") | .object.sha')
        echo "sha: $sha"

        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ inputs.repo }}/git/refs \
          -f "ref=refs/tags/${{ inputs.tag }}" -f "sha=$sha"