# This workflow is intended to be used to test. The main branch version does nothing. 
# It should not be changed in the main branch.
name: Workflow Sandbox

on:
  workflow_dispatch:

jobs:
  do-something:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    steps: # a workflow must have a step, if false makes it not actually run
    - uses: CDCR-OMS-PVDTS/.github/.github/actions/Set-Git-Tag@AB#23526-SetGitTag
      name: Set Git Tag
      continue-on-error: true
      with:
        repo: '${{ github.repository }}'
        # ref: "RunWorkflow.v.1.0.0"
        ref: "jacob.test"
        tag: "jacob.test.tag"
    - uses: CDCR-OMS-PVDTS/.github/.github/actions/Set-Git-Tag@AB#23526-SetGitTag
      name: Set Git Tag
      continue-on-error: true
      with:
        repo: '${{ github.repository }}'
        ref: "AB#23526-SetGitTag"
        tag: "jacob.test.branch"
    - uses: CDCR-OMS-PVDTS/.github/.github/actions/Set-Git-Tag@AB#23526-SetGitTag
      name: Set Git Tag
      continue-on-error: true
      with:
        repo: '${{ github.repository }}'
        # ref: "8c2d4e05f98820f340cd904d76a17759ac8734db"
        ref: "632821fb7d055b6b716d00dac472aae0a951a0ca"
        tag: "jacob.test.sha"