# This workflow is intended to be used to test. The main branch version does nothing. 
# It should not be changed in the main branch.
name: Workflow Sandbox

on:
  workflow_dispatch:

jobs:
  do-something:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    steps: # a workflow must have a step, if false makes it not actually run
      - uses: CDCR-OMS-PVDTS/.github/.github/actions/Set-Git-Tag@AB#23526-SetGitTag
        name: Set Git Tag
        with:
          repo: '${{ github.repository }}'
          ref: "AB#23526-SetGitTag"
          tag: "jacob.test"