# This workflow is intended to be used to test. The main branch version does nothing. 
# It should not be changed in the main branch.
name: Workflow Sandbox

on:
  workflow_dispatch:

    
env:
  GH_TOKEN: ${{ secrets.PAT }}

jobs:
  do-something:
    runs-on: ubuntu-latest
    steps: # a workflow must have a step, if false makes it not actually run
      - name: Create Deployment
        id: create
        uses: CDCR-OMS-PVDTS/.github/.github/actions/Create-Deployment@29474-DeploymentActions
        with:
          repo: ${{ github.repository }}
          ref: jacob.test
          task: my-task
          environment: sandbox
          description: 'My deployment description'
          workflow: ${{ github.workflow }}
          workflow_details: ${{ toJson(github) }}
          workflow_url: ${{ github.workflow_ref }}
          initial_state: pending
      - name: Set In Progress
        uses: CDCR-OMS-PVDTS/.github/.github/actions/Set-Deployment-Status@29474-DeploymentActions
        with:
          repo: ${{ github.repository }}
          deployment_id: ${{ steps.create.outputs.Deployment_ID }}
          state: in_progress
          description: 'Setting deployment to in-progress'
      - name: Get Deployment by ID
        uses: CDCR-OMS-PVDTS/.github/.github/actions/Get-Deployment@29474-DeploymentActions
        with:
          repo: ${{ github.repository }}
          id: ${{ steps.create.outputs.Deployment_ID }}
      - name: Set Success
        uses: CDCR-OMS-PVDTS/.github/.github/actions/Set-Deployment-Status@29474-DeploymentActions
        with:
          repo: ${{ github.repository }}
          deployment_id: ${{ steps.create.outputs.Deployment_ID }}
          state: success
          description: 'Setting deployment to success'
      - name: Get Deployment by environment
        uses: CDCR-OMS-PVDTS/.github/.github/actions/Get-Deployment@29474-DeploymentActions
        with:
          repo: ${{ github.repository }}
          environment: sandbox
      - name: Get Deployment by environment and success
        uses: CDCR-OMS-PVDTS/.github/.github/actions/Get-Deployment@29474-DeploymentActions
        with:
          repo: ${{ github.repository }}
          environment: sandbox
          status: success